import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#dae2fd",
        "on-tertiary-fixed": "#001c39",
        "on-secondary-fixed": "#111c2d",
        "on-secondary": "#263143",
        "inverse-primary": "#0053db",
        "inverse-on-surface": "#283044",
        "surface-bright": "#31394d",
        "surface-container": "#171f33",
        secondary: "#bcc7de",
        primary: "#b4c5ff",
        "primary-container": "#2563eb",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary-container": "#196fc0",
        "surface-dim": "#0b1326",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#bcc7de",
        "on-secondary-container": "#aeb9d0",
        "secondary-fixed": "#d8e3fb",
        tertiary: "#a4c9ff",
        "surface-container-highest": "#2d3449",
        "secondary-container": "#3e495d",
        background: "#0b1326",
        "tertiary-fixed-dim": "#a4c9ff",
        "on-tertiary-container": "#ebf1ff",
        "inverse-surface": "#dae2fd",
        "surface-container-lowest": "#060e20",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-container": "#eeefff",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-high": "#222a3d",
        "on-error-container": "#ffdad6",
        "on-surface": "#dae2fd",
        "on-primary-fixed": "#00174b",
        error: "#ffb4ab",
        "surface-variant": "#2d3449",
        "on-tertiary-fixed-variant": "#004883",
        "surface-container-low": "#131b2e",
        "on-error": "#690005",
        "on-primary": "#002a78",
        surface: "#0b1326",
        "on-surface-variant": "#c3c6d7",
        "outline-variant": "#434655",
        "tertiary-fixed": "#d4e3ff",
        outline: "#8d90a0",
        "surface-tint": "#b4c5ff",
        "on-tertiary": "#00315d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "section-gap-mobile": "64px",
        "section-gap-desktop": "120px",
        "margin-safe": "32px",
      },
      fontFamily: {
        "label-sm": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        "headline-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": [
          "12px",
          { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "48px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
